### ISSUE TITLE
App Crashed with this error java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Nomanghous** [acodexm/Panorama360#3]
Hello i am just new to this subject. I have compiled and build your source code successfully but when i tried to use the application it crashed with the following error. 
Thanks in Advance :)
May be this info helps:
I am using Windows 10 and Android studio v3.0.1
 
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/study.acodexm-1/base.apk"],nativeLibraryDirectories=[/data/app/study.acodexm-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libopencv_java3.so"
                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                   at java.lang.System.loadLibrary(System.java:989)
                                                                   at study.acodexm.MainActivity.<clinit>(MainActivity.java:61)
                                                                   at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                   at java.lang.Class.newInstance(Class.java:1572)
                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Nomanghous** [comment]
UPDATE: I have fixed that by copying "opencv_java3.so" from opencv sdk. 
Now error is same but file name is different. Please have a look at screenshot. 

![err](https://user-images.githubusercontent.com/12783763/35528617-3e7ac06a-0550-11e8-95c8-38272750cf9b.PNG)

**Comment by Nomanghous** [comment]
@acodexm any help please?

**Comment by shanavajk** [comment]
Can u please post the content of android.mk file

**Comment by acodexm** [comment]
https://github.com/acodexm/Panorama360/blob/master/android/src/main/jni/TEMPLATE_Android.mk
