### ISSUE TITLE
Doc: suggest adding these steps for Android Studio

### ISSUE THREAD

**Issue by markdeaton** [acodexm/Panorama360#9]
Here are some steps I needed to perform in getting the app to compile in Android Studio; not all of them are obvious; documenting them might save others some time.

1. Download old Android ndk r15c
1. Add to local.properties: ndk.dir=c\:\\\\android\\\\sdk\\\\ndk\\\\android-ndk-r15c
1. [Desktop module  build.gradle, line 32 ](https://github.com/acodexm/Panorama360/blob/1602ff04221c2415170a9a69eff688c2d4dad575/desktop/build.gradle#L32) change ".classesDir" to ".classesDirs"
1. Download OpenCV 3.3.1 https://github.com/opencv/opencv/archive/3.3.1.zip and extract it into the top directory of the project
1. Copy android/src/main/jni/TEMPLATE_Android.mk to Android.mk
1. In Android.mk set OPENCVROOT var to the OpenCV SDK 3.3.1 downloaded above (e.g. C:/Projects/Android/Panorama360/OpenCV-android-sdk)

**Comment by cybenauts** [comment]
Thank you for your suggestions, I am able to build the app, but getting the following error when the activity opens

`05-18 19:21:50.841 20496-20496/study.acodexm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: study.acodexm, PID: 20496
    java.lang.NoSuchMethodError: No static method stream([Ljava/lang/Object;)Ljava/util/stream/Stream; in class Ljava/util/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in /system/framework/core-libart.jar)
        at study.acodexm.f.t.a(Unknown Source)
        at study.acodexm.MainActivity.t(Unknown Source)
        at study.acodexm.MainActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6316)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2421)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2530)
        at android.app.ActivityThread.access$1100(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5600)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by markdeaton** [comment]
@cybenauts Is it possible you're using an older version of Android?
https://stackoverflow.com/questions/39515035/is-it-possible-to-use-the-java-8-stream-api-on-android-api-24

**Comment by salamay** [comment]
> Thank you for your suggestions, I am able to build the app, but getting the following error when the activity opens
> 
> `05-18 19:21:50.841 20496-20496/study.acodexm E/AndroidRuntime: FATAL EXCEPTION: main Process: study.acodexm, PID: 20496 java.lang.NoSuchMethodError: No static method stream([Ljava/lang/Object;)Ljava/util/stream/Stream; in class Ljava/util/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in /system/framework/core-libart.jar) at study.acodexm.f.t.a(Unknown Source) at study.acodexm.MainActivity.t(Unknown Source) at study.acodexm.MainActivity.onCreate(Unknown Source) at android.app.Activity.performCreate(Activity.java:6316) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2421) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2530) at android.app.ActivityThread.access$1100(ActivityThread.java:154) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5600) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`



> Here are some steps I needed to perform in getting the app to compile in Android Studio; not all of them are obvious; documenting them might save others some time.
> 
> 1. Download old Android ndk r15c
> 2. Add to local.properties: ndk.dir=c:\\android\\sdk\\ndk\\android-ndk-r15c
> 3. [Desktop module  build.gradle, line 32 ](https://github.com/acodexm/Panorama360/blob/1602ff04221c2415170a9a69eff688c2d4dad575/desktop/build.gradle#L32) change ".classesDir" to ".classesDirs"
> 4. Download OpenCV 3.3.1 https://github.com/opencv/opencv/archive/3.3.1.zip and extract it into the top directory of the project
> 5. Copy android/src/main/jni/TEMPLATE_Android.mk to Android.mk
> 6. In Android.mk set OPENCVROOT var to the OpenCV SDK 3.3.1 downloaded above (e.g. C:/Projects/Android/Panorama360/OpenCV-android-sdk)

I didn't understand  the 5th step

**Comment by markdeaton** [comment]
@salamay Step 5 refers to the source code for this git: https://github.com/acodexm/Panorama360/tree/master/android/src/main/jni

In that directory, currently there's Application.mk and TEMPLATE_Android.mk. I'm suggesting you copy TEMPLATE_Android.mk to the same directory and rename it "Android.mk" because that's the NDK build system seems to be looking for (not "Application.mk").

**Comment by salamay** [comment]
> @salamay Step 5 refers to the source code for this git: https://github.com/acodexm/Panorama360/tree/master/android/src/main/jni
> 
> In that directory, currently there's Application.mk and TEMPLATE_Android.mk. I'm suggesting you copy TEMPLATE_Android.mk to the same directory and rename it "Android.mk" because that's the NDK build system seems to be looking for (not "Application.mk").

Thanks... It has compiled.....but i don't know how to operate the app... It doesn't seam to capture any photo in any mode
